-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.



CREATE TABLE IF NOT EXISTS public."Doctors"
(
    doctorid serial NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (doctorid)
);


CREATE TABLE IF NOT EXISTS public."Patients"
(
    patientid serial NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (patientid)
);

CREATE TABLE IF NOT EXISTS public."Visits"
(
    visitid serial NOT NULL,
    doctorid numeric NOT NULL,
    patientid numeric NOT NULL,
    date date NOT NULL,
    room text,
    PRIMARY KEY (visitid)
);

CREATE TABLE IF NOT EXISTS public."Diseases"
(
    diseaseid serial NOT NULL,
    title text NOT NULL,
    visitid numeric NOT NULL,
    PRIMARY KEY (diseaseid)
);


ALTER TABLE IF EXISTS public."Visits"
    ADD CONSTRAINT doctorid FOREIGN KEY (doctorid)
    REFERENCES public."Doctors" (doctorid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Visits"
    ADD CONSTRAINT patientid FOREIGN KEY (patientid)
    REFERENCES public."Patients" (patientid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Diseases"
    ADD CONSTRAINT visitid FOREIGN KEY (visitid)
    REFERENCES public."Visits" (visitid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	
	INSERT INTO public.Doctors (name) VALUES ('Mark Ivanov'), ('John Doe'), ('Krista Boyd');
	INSERT INTO public.Patients (name) VALUES ('Sonja Zind'), ('Ella Kryshtal'), ('Anna Dikarev');
	INSERT INTO public.Visits 
(doctorid, patientid, date, room) VALUES
(1, 2, '2023-08-30 12:00:00', 'm23'),
(2, 3, '2023-08-30 08:00:00', 'r13'),
(3, 3, '2023-08-30 08:00:00', 'r13');
INSERT INTO public.Diseases 
(title, visitid) VALUES
('Liver failure', 1),
('Flu', 1),
('Tumor', 2),
('Anemia', 3);





