-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS Team
(
    id integer NOT NULL,
    team text NOT NULL,
    PRIMARY KEY (id)
);

INSERT into Team(id, team) VALUES
(1, 'Lakers'),
(2, 'Aligators'),
(3, 'Bears');

CREATE TABLE IF NOT EXISTS player
(
    id integer NOT NULL,
    name text NOT NULL,
    teamid integer NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT teamid FOREIGN KEY (teamid)
    REFERENCES Team (id)
);
INSERT INTO player(id, name, teamid) VALUES
(1, 'Thomas', 1),
(2, 'Blake', 2),
(3, 'Rob', 3);

CREATE TABLE IF NOT EXISTS referres
(
    id integer NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);
INSERT INTO referres(id, name) VALUES
(1, 'Kristine');


CREATE TABLE IF NOT EXISTS Season
(
    id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    PRIMARY KEY (id)
);
INSERT INTO Season (id, start_date, end_date) VALUES
(1, '2023-02-15', '2023-06-10');

CREATE TABLE IF NOT EXISTS Game
(
    id integer NOT NULL,
    team1id integer NOT NULL,
    team2id integer NOT NULL,
    refereesid integer NOT NULL,
    gametime time NOT NULL,
    season_id integer NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT team1id FOREIGN KEY (team1id)
    REFERENCES Team (id),
    CONSTRAINT team2id FOREIGN KEY (team2id)
    REFERENCES Team (id),
    CONSTRAINT referees FOREIGN KEY (refereesid)
    REFERENCES referres (id),
    CONSTRAINT seaon_id FOREIGN KEY (season_id)
    REFERENCES Season (id)
);
INSERT INTO Game(id, team1id, team2id, refereesid, gametime, season_id) VALUES
(1,1,2,1,'12:00:00',1);

CREATE TABLE IF NOT EXISTS goals
(
    id integer NOT NULL,
    gameid integer NOT NULL,
    playerid integer NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT playerid FOREIGN KEY (playerid)
    REFERENCES player (id),
    CONSTRAINT gameid FOREIGN KEY (gameid)
    REFERENCES Game (id) 
);
INSERT INTO goals (id, gameid, playerid) VALUES
(1, 1, 1);



END;

SELECT *
FROM goals
JOIN Game ON gameid = Game.id
JOIN player ON playerid = player.id
JOIN Team ON teamid = team.id